services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: siv-sqlserver
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Siv2026!Vuelos"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - siv_sqldata:/var/opt/mssql

volumes:
  siv_sqldata: